SELECT 'ALL (007+008+009) verification' AS report, DATABASE() AS db, VERSION() AS mysql_version,
 (SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='metric_type_accounts') AS x007a_metric_type_accounts,
 (SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='achievements') AS x007a_achievements,
 (SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='achievement_evidence') AS x007a_evidence,
 (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='gps_target_metrics' AND COLUMN_NAME='calculation_version') AS x007a_gps_cols,
 (SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='achievement_evidence' AND INDEX_NAME='uq_evidence_metric_snapshot') AS x007b_snapshot_guard,
 (SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='calendar_events') AS x008_calendar_events,
 (SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='calendar_event_links') AS x008_event_links,
 (SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND CONSTRAINT_NAME='chk_cal_time_shape') AS x008_time_check,
 (SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='sessions') AS x009_sessions,
 (SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ('session_participants','session_agenda_items','session_notes','session_decisions','session_entity_links','session_activities')) AS x009_child_tables,
 (SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND CONSTRAINT_NAME='fk_sessions_company') AS x009_fk_company,
 (SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND CONSTRAINT_NAME='fk_sessions_event') AS x009_fk_event,
 (SELECT COUNT(*) FROM achievement_evidence WHERE source_type='metric_snapshot' GROUP BY achievement_id HAVING COUNT(*)>1 LIMIT 1) IS NOT NULL AS inv_dup_snapshot,
 (SELECT COUNT(*) FROM achievement_evidence e LEFT JOIN achievements a ON a.id=e.achievement_id WHERE a.id IS NULL) AS inv_orphan_evidence,
 (SELECT COUNT(*) FROM achievements a JOIN gps_targets t ON t.id=a.gps_target_id WHERE t.company_id<>a.company_id) AS inv_cross_company,
 (SELECT COUNT(*) FROM calendar_events WHERE NOT ((all_day=1 AND start_date IS NOT NULL AND end_date IS NOT NULL AND start_at IS NULL AND end_at IS NULL) OR (all_day=0 AND start_at IS NOT NULL AND end_at IS NOT NULL AND timezone IS NOT NULL AND start_date IS NULL AND end_date IS NULL))) AS inv_bad_time_shape,
 (SELECT COUNT(*) FROM sessions WHERE tenant_id IS NULL) AS inv_sessions_missing_tenant,
 (SELECT COUNT(*) FROM session_agenda_items x LEFT JOIN sessions s ON s.id=x.session_id WHERE s.id IS NULL) AS inv_orphan_agenda,
 (SELECT COUNT(*) FROM session_notes x LEFT JOIN sessions s ON s.id=x.session_id WHERE s.id IS NULL) AS inv_orphan_notes,
 (SELECT COUNT(*) FROM session_decisions x LEFT JOIN sessions s ON s.id=x.session_id WHERE s.id IS NULL) AS inv_orphan_decisions,
 (SELECT COUNT(*) FROM session_entity_links x LEFT JOIN sessions s ON s.id=x.session_id WHERE s.id IS NULL) AS inv_orphan_links,
 (SELECT COUNT(*) FROM session_activities x LEFT JOIN sessions s ON s.id=x.session_id WHERE s.id IS NULL) AS inv_orphan_activities,
 (SELECT COUNT(*) FROM company_financial_yearly_stats WHERE account_id IS NULL) AS info_unresolved_rows,
 (SELECT COUNT(DISTINCT company_id) FROM company_accounts WHERE account_type='export_revenue' AND is_active=1) AS info_export_account_companies;
